### ISSUE TITLE
FTICR-MS aromatic/aliphatic peaks

### ISSUE THREAD

**Issue by Erin-Rooney** [kaizadp/tes_3soils_2019#29]
@kaizadp 

This is where I got hung up in my code.

Your code:
https://github.com/kaizadp/tes_3soils_2019/blob/9d73f923415639a15dcd842e6ecec65ffe60ef33/code/8b-fticr_abundance.R#L87

My code:
https://github.com/Erin-Rooney/FTC-transect/blob/29fdc7531dd36a962713cce30882ecb51a763e68/code/fticr_kp_backup.R#L318

**Comment by kaizadp** [comment]
What error/output?

**Comment by Erin-Rooney** [comment]
No error, I just want to go over how to do the Dunnett stuff because I got a little lost reading through the code on my own. 

These are the figures I've made without using the Dunnett stuff.

![image](https://user-images.githubusercontent.com/61806923/95111306-26f04700-06f4-11eb-9964-40dc69dd3d45.png)

**Comment by kaizadp** [comment]
Yep, let's over that today. I don't think you need Dunnett Test for these data, but let's chat about it.
